# permissions for end users to view edges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-viewer-role
rules:
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - edges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - edges/status
  verbs:
  - get
