# permissions for end users to view maxcuts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maxcut-viewer-role
rules:
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - maxcuts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - maxcuts/status
  verbs:
  - get
