# permissions for end users to edit maxcuts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maxcut-editor-role
rules:
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - maxcuts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - maxcuts/status
  verbs:
  - get
