# permissions for end users to view vertices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vertex-viewer-role
rules:
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - vertices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graph.example.valinux.co.jp
  resources:
  - vertices/status
  verbs:
  - get
